version: "3"

# このconfigは、 dockerでMisskey本体を起動せず、 redisとpostgresql などだけを起動します

services:
  dragonfly:
    restart: always
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    command: dragonfly --logtostderr --version_check=false --bind=0.0.0.0 --port=6379 --maxclients=64000 --maxmemory=0 --hz=100 --snapshot_cron=* * * * * --default_lua_flags=allow-undeclared-keys --pipeline_squash=0 --multi_exec_squash=false --conn_io_threads=4 --epoll_file_threads=4 --proactor_threads=4
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

#  meilisearch:
#    restart: always
#    image: getmeili/meilisearch:v1.3.4
#    environment:
#      - MEILI_NO_ANALYTICS=true
#      - MEILI_ENV=production
#    env_file:
#      - .config/meilisearch.env
#    volumes:
#      - ./meili_data:/meili_data

