ARG BASE_IMAGE=ghcr.io/misskeyio/misskey:main
FROM ${BASE_IMAGE}

RUN pnpm add --workspace-root \
    @opentelemetry/api \
    @opentelemetry/sdk-node \
    @opentelemetry/auto-instrumentations-node \
    @opentelemetry/exporter-trace-otlp-http \
    @opentelemetry/exporter-metrics-otlp-http \
    @opentelemetry/sdk-metrics \
    @opentelemetry/resources \
    @opentelemetry/semantic-conventions