packages:
  - packages/backend
  - packages/frontend-shared
  - packages/frontend
  - packages/frontend-embed
  - packages/sw
  - packages/misskey-js
  - packages/misskey-js/generator
  - packages/misskey-reversi
  - packages/misskey-bubble-game

catalog:
  '@authenio/samlify-node-xmllint': 2.0.0
  '@aws-sdk/client-s3': 3.922.0
  '@aws-sdk/lib-storage': 3.922.0
  '@bull-board/api': 6.14.0
  '@bull-board/fastify': 6.14.0
  '@bull-board/ui': 6.14.0
  '@discordapp/twemoji': 16.0.1
  '@fastify/accepts': 5.0.3
  '@fastify/cookie': 11.0.2
  '@fastify/cors': 11.1.0
  '@fastify/express': 4.0.2
  '@fastify/formbody': 8.0.2
  '@fastify/http-proxy': 11.3.0
  '@fastify/multipart': 9.3.0
  '@fastify/static': 8.3.0
  '@fastify/view': 11.1.1
  '@github/webauthn-json': 2.1.1
  '@isaacs/ttlcache': 2.0.1
  '@jest/globals': 30.2.0
  '@mcaptcha/vanilla-glue': 0.1.0-alpha-3
  '@microsoft/api-extractor': 7.53.3
  '@misskey-dev/browser-image-resizer': 2024.1.0
  '@misskey-dev/eslint-plugin': 2.1.0
  '@misskey-dev/sharp-read-bmp': 1.3.0
  '@napi-rs/canvas': 0.1.81
  '@nestjs/common': 11.1.8
  '@nestjs/core': 11.1.8
  '@nestjs/platform-express': 11.1.8
  '@nestjs/testing': 11.1.8
  '@opensearch-project/opensearch': 3.5.1
  '@peertube/http-signature': 1.7.0
  '@readme/openapi-parser': 5.2.0
  '@rollup/plugin-json': 6.1.0
  '@rollup/plugin-replace': 6.0.3
  '@rollup/plugin-typescript': 12.3.0
  '@rollup/pluginutils': 5.3.0
  '@sentry/node': 10.22.0
  '@sentry/profiling-node': 10.22.0
  '@sentry/vue': 10.22.0
  '@simplewebauthn/browser': 13.2.2
  '@simplewebauthn/server': 13.2.2
  '@sinonjs/fake-timers': 15.0.0
  '@smithy/node-http-handler': 4.4.4
  '@storybook/addon-actions': 9.0.8
  '@storybook/addon-essentials': 8.6.14
  '@storybook/addon-interactions': 8.6.14
  '@storybook/addon-links': 10.0.2
  '@storybook/addon-mdx-gfm': 8.6.14
  '@storybook/addon-storysource': 8.6.14
  '@storybook/blocks': 8.6.14
  '@storybook/components': 8.6.14
  '@storybook/core-events': 8.6.14
  '@storybook/manager-api': 8.6.14
  '@storybook/preview-api': 8.6.14
  '@storybook/react': 10.0.2
  '@storybook/react-vite': 10.0.2
  '@storybook/test': 8.6.14
  '@storybook/theming': 8.6.14
  '@storybook/types': 8.6.14
  '@storybook/vue3': 10.0.2
  '@storybook/vue3-vite': 10.0.2
  '@swc/cli': 0.7.8
  '@swc/core': 1.14.0
  '@swc/core-darwin-arm64': 1.14.0
  '@swc/core-darwin-x64': 1.14.0
  '@swc/core-linux-arm-gnueabihf': 1.14.0
  '@swc/core-linux-arm64-gnu': 1.14.0
  '@swc/core-linux-arm64-musl': 1.14.0
  '@swc/core-linux-x64-gnu': 1.14.0
  '@swc/core-linux-x64-musl': 1.14.0
  '@swc/core-win32-arm64-msvc': 1.14.0
  '@swc/core-win32-ia32-msvc': 1.14.0
  '@swc/core-win32-x64-msvc': 1.14.0
  '@swc/jest': 0.2.39
  '@syuilo/aiscript': 1.1.2
  '@tabler/icons-webfont': 3.35.0
  '@testing-library/vue': 8.1.0
  '@twemoji/parser': 16.0.0
  '@types/accepts': 1.3.7
  '@types/archiver': 7.0.0
  '@types/bcryptjs': 3.0.0
  '@types/body-parser': 1.19.6
  '@types/canvas-confetti': 1.9.0
  '@types/color-convert': 2.0.4
  '@types/content-disposition': 0.5.9
  '@types/escape-regexp': 0.0.3
  '@types/estree': 1.0.8
  '@types/fluent-ffmpeg': 2.1.28
  '@types/htmlescape': 1.1.3
  '@types/http-link-header': 1.0.7
  '@types/jest': 30.0.0
  '@types/js-yaml': 4.0.9
  '@types/jsdom': 21.1.7
  '@types/jsonld': 1.5.15
  '@types/jsrsasign': 10.5.15
  '@types/matter-js': 0.20.2
  '@types/micromatch': 4.0.10
  '@types/mime-types': 3.0.1
  '@types/ms': 2.1.0
  '@types/node': 24.9.2
  '@types/node-forge': 1.3.14
  '@types/nodemailer': 7.0.3
  '@types/oauth': 0.9.6
  '@types/oauth2orize': 1.11.5
  '@types/oauth2orize-pkce': 0.1.2
  '@types/pg': 8.15.6
  '@types/pug': 2.0.10
  '@types/qrcode': 1.5.6
  '@types/random-seed': 0.3.5
  '@types/ratelimiter': 3.4.6
  '@types/rename': 1.0.7
  '@types/sanitize-html': 2.16.0
  '@types/seedrandom': 3.0.8
  '@types/semver': 7.7.1
  '@types/serviceworker': 0.0.164
  '@types/simple-oauth2': 5.0.7
  '@types/sinonjs__fake-timers': 15.0.1
  '@types/supertest': 6.0.3
  '@types/three': 0.181.0
  '@types/throttle-debounce': 5.0.2
  '@types/tinycolor2': 1.4.6
  '@types/tmp': 0.2.6
  '@types/uuid': 11.0.0
  '@types/vary': 1.1.3
  '@types/web-push': 3.6.4
  '@types/ws': 8.18.1
  '@typescript-eslint/eslint-plugin': 8.46.2
  '@typescript-eslint/parser': 8.46.2
  '@vitejs/plugin-vue': 6.0.1
  '@vitest/coverage-v8': 4.0.6
  '@vue/compiler-core': 3.5.22
  '@vue/compiler-sfc': 3.5.22
  '@vue/runtime-core': 3.5.22
  accepts: 1.3.8
  acorn: 8.15.0
  aiscript-vscode: github:aiscript-dev/aiscript-vscode#v0.1.16
  ajv: 8.17.1
  archiver: 7.0.1
  astring: 1.9.0
  async-mutex: 0.5.0
  aws-sdk-client-mock: 4.1.0
  bcryptjs: 3.0.2
  blurhash: 2.0.5
  body-parser: 2.2.0
  broadcast-channel: 7.2.0
  bufferutil: 4.0.9
  bullmq: 5.63.0
  buraha: 0.0.1
  cacheable-lookup: 7.0.0
  canvas-confetti: 1.9.4
  cbor: 10.0.11
  chalk: 5.6.2
  chalk-template: 1.1.2
  chart.js: 4.5.1
  chartjs-adapter-date-fns: 3.0.0
  chartjs-chart-matrix: 3.0.0
  chartjs-plugin-gradient: 0.6.1
  chartjs-plugin-zoom: 2.2.0
  chromatic: 13.3.3
  cli-highlight: 2.1.11
  color-convert: 3.1.2
  compare-versions: 6.1.1
  content-disposition: 0.5.4
  crc-32: 1.2.2
  cropperjs: 2.1.0
  cross-env: 10.1.0
  cssnano: 7.1.2
  cypress: 15.5.0
  date-fns: 4.1.0
  deep-email-validator: 0.1.21
  esbuild: 0.25.12
  escape-regexp: 0.0.1
  eslint: 9.39.0
  eslint-plugin-import: 2.32.0
  eslint-plugin-vue: 10.5.1
  estree-walker: 3.0.3
  eventemitter3: 5.0.1
  execa: 9.6.0
  fast-glob: 3.3.3
  fastify: 5.6.1
  fastify-http-errors-enhanced: 6.0.1
  fastify-raw-body: 5.0.0
  feed: 5.1.0
  file-type: 21.0.0
  fkill: 9.0.0
  fluent-ffmpeg: 2.1.3
  form-data: 4.0.4
  glob: 11.0.3
  globals: 16.5.0
  got: 14.6.2
  happy-dom: 20.0.10
  hpagent: 1.2.0
  htmlescape: 1.1.1
  http-link-header: 1.1.3
  idb-keyval: 6.2.2
  ignore-walk: 8.0.0
  insert-text-at-cursor: 0.3.0
  ioredis: 5.8.2
  ip-cidr: 4.0.2
  ipaddr.js: 2.2.0
  is-file-animated: 1.0.2
  is-svg: 6.1.0
  jest: 30.2.0
  jest-fetch-mock: 3.0.3
  jest-mock: 30.2.0
  jest-websocket-mock: 2.5.0
  jose: 6.1.0
  js-yaml: 4.1.0
  jsdom: 26.1.0
  json5: 2.2.3
  jsonld: 8.3.3
  jsrsasign: 11.1.0
  juice: 11.0.3
  magic-string: 0.30.21
  matter-js: 0.20.0
  meilisearch: 0.54.0
  mfm-js: 0.25.0
  microformats-parser: 2.0.4
  micromatch: 4.0.8
  mime-types: 3.0.1
  minimatch: 10.1.1
  mock-socket: 9.3.1
  ms: 3.0.0-canary.1
  msw: 2.11.6
  msw-storybook-addon: 2.0.6
  nanoid: 5.1.6
  ncp: 2.0.0
  nested-property: 4.0.0
  node-fetch: 3.3.2
  node-forge: 1.3.1
  nodemailer: 7.0.10
  nodemon: 3.1.10
  nsfwjs: 4.2.0
  oauth: 0.10.2
  oauth2orize: 1.12.0
  oauth2orize-pkce: 0.1.2
  openapi-types: 12.1.3
  openapi-typescript: 7.10.1
  os-utils: 0.0.14
  otpauth: 9.4.1
  parse5: 7.3.0
  pg: 8.16.3
  photoswipe: 5.4.4
  pid-port: 2.0.0
  pino: 10.1.0
  pino-pretty: 13.1.2
  pkce-challenge: 5.0.0
  pnpm: 10.20.0
  postcss: 8.5.6
  prettier: 3.6.2
  probe-image-size: 7.2.3
  promise-limit: 2.7.0
  psl: 1.15.0
  pug: 3.0.3
  punycode.js: 2.3.1
  qrcode: 1.5.4
  random-seed: 0.3.0
  ratelimiter: 3.4.1
  re2: 1.22.1
  react: 19.2.0
  react-dom: 19.2.0
  redis-lock: 1.0.0
  reflect-metadata: 0.2.2
  rename: 1.0.4
  rollup: 4.52.5
  rss-parser: 3.13.0
  rxjs: 7.8.2
  samlify: 2.10.1
  sanitize-html: 2.17.0
  sass: 1.93.3
  secure-json-parse: 4.1.0
  seedrandom: 3.0.5
  shiki: 3.14.0
  simple-oauth2: 5.1.0
  slacc: 0.0.10
  slacc-android-arm-eabi: 0.0.10
  slacc-android-arm64: 0.0.10
  slacc-darwin-arm64: 0.0.10
  slacc-darwin-universal: 0.0.10
  slacc-darwin-x64: 0.0.10
  slacc-freebsd-x64: 0.0.10
  slacc-linux-arm-gnueabihf: 0.0.10
  slacc-linux-arm64-gnu: 0.0.10
  slacc-linux-arm64-musl: 0.0.10
  slacc-linux-x64-gnu: 0.0.10
  slacc-linux-x64-musl: 0.0.10
  slacc-win32-arm64-msvc: 0.0.10
  slacc-win32-x64-msvc: 0.0.10
  start-server-and-test: 2.1.2
  storybook: 10.0.2
  storybook-addon-misskey-theme: github:misskey-dev/storybook-addon-misskey-theme
  strict-event-emitter-types: 2.0.0
  stringz: 2.1.0
  supertest: 7.1.4
  systeminformation: 5.27.11
  terser: 5.44.0
  textarea-caret: 3.1.0
  three: 0.181.0
  throttle-debounce: 5.0.2
  tinycolor2: 1.6.0
  tmp: 0.2.5
  ts-case-convert: 2.1.0
  tsc-alias: 1.8.16
  tsconfig-paths: 4.2.0
  tsd: 0.33.0
  tsx: 4.20.6
  typeorm: 0.3.27
  typescript: 5.9.3
  ulid: 3.0.1
  utf-8-validate: 6.0.5
  uuid: 13.0.0
  v-code-diff: 1.13.1
  vary: 1.1.2
  vite: 7.1.12
  vite-plugin-turbosnap: 1.0.3
  vitest: 4.0.6
  vitest-fetch-mock: 0.4.5
  vue: 3.5.22
  vue-component-type-helpers: 3.1.2
  vue-eslint-parser: 10.2.0
  vue-gtag: 3.6.3
  vue-tsc: 3.1.2
  vuedraggable: next
  wanakana: 5.3.1
  web-push: 3.6.7
  webgl-audiovisualizer: github:MisskeyIO/webgl-audiovisualizer
  ws: 8.18.3
  xev: 3.0.2
  xmlbuilder: 15.1.1

catalogMode: strict

ignorePatchFailures: false

ignoredBuiltDependencies:
  - '@sentry-internal/node-cpu-profiler'
  - unrs-resolver

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@sentry/profiling-node'
  - '@swc/core'
  - '@tensorflow/tfjs-node'
  - bufferutil
  - canvas
  - core-js
  - cypress
  - esbuild
  - msgpackr-extract
  - msw
  - nice-napi
  - re2
  - sharp
  - utf-8-validate
  - v-code-diff
  - vue-demi

overrides:
  '@aiscript-dev/aiscript-languageserver': '-'
  '@misskey-dev/summaly': github:MisskeyIO/summaly#5.2.1-io.1
  '@tensorflow/tfjs': 4.22.0
  '@tensorflow/tfjs-core': 4.22.0
  '@tensorflow/tfjs-node': 4.22.0
  '@types/punycode': 2.1.4
  '@types/punycode.js': npm:@types/punycode@2.1.4
  axios: 1.13.1
  chokidar: 4.0.3
  cookie: 1.0.2
  cookie-signature: 1.2.2
  debug: 4.4.3
  jpeg-js: 0.4.4
  lodash: 4.17.21
  sharp: 0.34.4
  tough-cookie: 6.0.0
  web-streams-polyfill: 4.2.0
