version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspace:cached

    command: sleep infinity

    networks:
      - internal_network
      - external_network

  dragonfly:
    restart: unless-stopped
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    command: dragonfly --logtostderr --version_check=false --bind=0.0.0.0 --port=6379 --maxclients=64000 --maxmemory=0 --hz=100 --snapshot_cron=* * * * * --default_lua_flags=allow-undeclared-keys --pipeline_squash=0 --multi_exec_squash=false --conn_io_threads=4 --epoll_file_threads=4 --proactor_threads=4
    ulimits:
      memlock: -1
    networks:
      - internal_network
    volumes:
      - dragonfly-data:/data

  db:
    restart: unless-stopped
    image: postgres:15-alpine
    networks:
      - internal_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: misskey
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

volumes:
  postgres-data:
  dragonfly-data:

networks:
  internal_network:
    internal: true
  external_network:
