name: Test (frontend)

on:
  push:
    branches:
      - main
      - next
      - beta
      - io
      - host
    paths:
      - packages/frontend/**
      # for permissions
      - packages/misskey-js/**
      - pnpm-lock.yaml
      - .github/workflows/test-frontend.yml
      - .github/misskey/test.yml
  pull_request:
    paths:
      - packages/frontend/**
      # for permissions
      - packages/misskey-js/**
      - pnpm-lock.yaml
      - .github/workflows/test-frontend.yml
      - .github/misskey/test.yml

permissions:
  contents: read

jobs:
  vitest:
    name: Unit tests (frontend)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.3.0
      with:
        fetch-depth: 0
        submodules: true
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.2.0
    - name: Use Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy Configure
      run: cp .github/misskey/test.yml .config
    - name: Build
      run: pnpm build
    - name: Test
      run: pnpm --filter frontend test-and-coverage
    - name: Upload Coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./packages/frontend/coverage/coverage-final.json
